# Site settings
title: Carolina Vaz 
description: Página Pessoal
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Carolina Vaz
user_description: Professora de Matemática da rede particular de ensino. Tenho formação em Licenciatura Plena pelo Centro Universitário de Belo Horizonte, Especializações em Docência do Ensino Superior e Medologias do Ensino da Matemática. Estou cursando o Mestrado Profissional (PROFMAT). Atualmente trabalho com 6º e 7º anos do ensino fundamental e 1ª série do Ensino Médio no Colégio Santa Maria Minas, Unidade Betim.
user_title: Professora de Matemática
email: carolvaz.mesquita@gmail.com
# github_username:  carolvazmesquita

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
